services:
  db:
    image: postgres:17.6
    container_name: metrics_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics_db
      TZ: "Europe/Kyiv"
      PGTZ: "Europe/Kyiv"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app-server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: metrics_server
    command: java -jar server.jar
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/metrics_db
      - TZ=Europe/Kyiv
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  app-core:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: metrics_core
    command: java -jar core.jar
    environment:
      - DB_URL=jdbc:postgresql://db:5432/metrics_db
      - TCP_PORT=9090
      - TZ=Europe/Kyiv
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: ./metrics-ui
      dockerfile: Dockerfile.frontend
    container_name: metrics_frontend
    ports:
      - "3000:80"
    depends_on:
      - app-server
      - app-core
    restart: always

volumes:
  pgdata:
